#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
touch scalarAdvection.foam
restore0Dir

nProcs=$1
mesh=$2

runApplication blockMesh

runApplication ../../../build/ReleaseCudaAll/bin/scalarAdvection


#------------------------------------------------------------------------------
