# SPDX-FileCopyrightText: 2023 - 2025 NeoN authors
#
# SPDX-License-Identifier: Unlicense

image: chihtaw/cuda-openfoam:v2412

workflow:
  rules:
    # Skip pipeline if only doc or Markdown files changed
    - changes:
        - doc/**/*
        - '*.md'
      when: never

    # Run pipeline for everything else
    - when: always

stages:
  - build-and-test

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 1

build-and-test-foamadapter:
  stage: build-and-test
  tags: ["nvidia-gpus"]
  before_script:
    # Install pre-commit
    - pip3 install --user --break-system-packages pre-commit
    - export PATH="$HOME/.local/bin:$PATH"

    # Show versions for debugging
    - cmake --version
    - clang++ --version || g++ --version
    - nvidia-smi
    - nvcc --version

  script:
    - ./ci_build-and-test.sh
