version = 1
SPDX-PackageName = "NeoFOAM"
SPDX-PackageSupplier = "NeoFOAM authors"
SPDX-PackageDownloadLocation = "https://github.com/exasim-project/NeoFOAM"

[[annotations]]
path = [
    ".github/**",  ".vscode/**.json", "AUTHORS.md",  "doc/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 NeoFOAM authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "CMakePresets.json", ".clang-format", ".clang-tidy", ".pre-commit-config.yaml", "spack.yaml", "REUSE.toml"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 - 2024 NeoFOAM authors"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = [
    "test/**",
     "benchmarkSuite/**",
     ".github/workflows/build.yaml",
     ".github/workflows/static_checks.yaml",
     ".vscode/c_cpp_properties.json",
     ".vscode/settings.json",
     "CHANGELOG.md",
     "README.md",
     ".gitmodules",
     "environment.yml"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 - 2024 NeoFOAM authors"
SPDX-License-Identifier = "Unlicense"
