#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
touch scalarAdvection.foam
restore0Dir

runApplication blockMesh

# runApplication ../../build/profiling/bin/scalarAdvection

#------------------------------------------------------------------------------
