#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
touch scalarAdvection.foam
restore0Dir

nProcs=$1
mesh=$2

runApplication blockMesh

foamDictionary system/controlDict -entry executor -set GPU
time ../../build/production/bin/scalarNeoFoamAdvection  > log.scalarNeoFoamAdvectionGPU

foamDictionary system/controlDict -entry executor -set CPU
time ../../build/production/bin/scalarNeoFoamAdvection  > log.scalarNeoFoamAdvectionCPU

foamDictionary system/controlDict -entry executor -set Serial
time ../../build/production/bin/scalarNeoFoamAdvection  > log.scalarNeoFoamAdvectionSerial

time ../../build/production/bin/scalarFoamAdvection > log.scalarFoamAdvectionSerial

runApplication decomposePar
runParallel ../../build/production/bin/scalarFoamAdvection

#------------------------------------------------------------------------------
