#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
touch test.foam

restore0Dir

runApplication blockMesh

runApplication ../../build/src/test/test_unstructuredMesh
runApplication ../../build/src/test/test_geometricFields
runApplication ../../build/src/test/test_operators 




#------------------------------------------------------------------------------
