name: Build FoamAdapter
run-name: 'Build workflow'

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  OMPI_MCA_rmaps_base_oversubscribe: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build FoamAdapter
    runs-on: ubuntu-latest
    if: "!contains(toJson(github.event.pull_request.labels.*.name), 'Skip-build')"
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - CC: clang
            CXX: clang++
          - CC: gcc
            CXX: g++
    steps:
     - name: Checkout to repository
       uses: actions/checkout@v4

     - name: Set up OpenFOAM
       uses: gerlero/setup-openfoam@v1
       with:
         openfoam-version: 2406

     - name: Install dependencies
       uses: gerlero/apt-install@v1
       with:
         packages: >-
           ninja-build
           clang-16
           gcc-10
           libomp-16-dev
           python3
           python3-dev
           build-essential
           libopenmpi-dev
           openmpi-bin

     - name: Get versions
       run: |
         clang --version
         ninja --version
         cmake --version

     - name: Build FoamAdapter
       run: |
         source /usr/lib/openfoam/openfoam2406/etc/bashrc || true
         CC=${{matrix.compiler.CC}} \
         CXX=${{matrix.compiler.CXX}} \
         cmake --preset develop \
           -DFOAMADAPTER_DEVEL_TOOLS=OFF \
           -DFOAMADAPTER_BUILD_BENCHMARKS=OFF \
           -DFOAMADAPTER_ENABLE_MPI_WITH_THREAD_SUPPORT=OFF
         cmake --build  --preset develop

     - name: Execute unit tests FoamAdapter
       run: |
         source /usr/lib/openfoam/openfoam2406/etc/bashrc || true
         ctest --preset develop

  build-python:
    runs-on: ubuntu-latest # may use an older version to test
    if: "!contains(toJson(github.event.pull_request.labels.*.name), 'Skip-build')"
    strategy:
      matrix:
        openfoam-version: [2406, 2412, 2506]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
      fail-fast: false
    name: FoamAdapter Python with OpenFOAM ${{ matrix.openfoam-version }}
    steps:
      - uses: actions/checkout@v5
      
      - name: Set up OpenFOAM
        uses: gerlero/setup-openfoam@v1
        with:
          openfoam-version: ${{ matrix.openfoam-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          uv run pip install -v .[all]
        
      - name: Test with pytest
        run: |
          uv run pytest