name: Changelog check
run-name: Changelog check

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  changelog:
    name: Changelog check
    runs-on: ubuntu-24.04
    if: "!contains(toJson(github.event.pull_request.labels.*.name), 'skip-changelog')"
    steps:
      - uses: actions/checkout@v4
      - uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: CHANGELOG.md
