name: GitHub-to-LRZ-GitLab Mirror (Project Token)

on:
  push:
    branches: ["**"]
    tags: ["**"]
  delete:
    branches: ["**"]
    tags: ["**"]

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone GitHub repo as bare
        run: |
          git clone --bare https://github.com/exasim-project/FoamAdapter.git

      - name: Push to LRZ GitLab (mirror)
        env:
          GITLAB_TOKEN_NAME: "github-mirror-token"
          GITLAB_PROJECT_TOKEN: ${{ secrets.GITLAB_PROJECT_TOKEN }}
        run: |
          cd FoamAdapter.git
          git push --mirror https://${GITLAB_TOKEN_NAME}:${GITLAB_PROJECT_TOKEN}@gitlab-ce.lrz.de/greole/foamadapter.git
